name: Hawk
main: me.islandscout.hawk.Hawk
version: DEV_13.8.2018
author: Islandscout
description: An anti-cheat system
commands:
    hawk:
        description: Basic information about Hawk Anti-Cheat
        usage: /<command>
permissions:
  hawk.cmd.*:
    description: Allows one to perform any Hawk command
    default: op
  hawk.cmd:
    description: Allows one to access help menu and GUI
    default: op
  hawk.notify:
    description: Allows one to recieve Hawk notifications
    default: op
